general:
  pipeline: "sap-cloud-sdk"
  buildTool: "mta"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    tmsUpload: false
steps:
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: "https://api.cf.us10.hana.ondemand.com" # please verify if this is your API endpoint. If not, please change it
      org: "bebdc7e1trial" # add your org here
      space: "dev" # add your space here
      credentialsId: "cfdeploy"
      appName: ""
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"